### ISSUE TITLE
Account Permissions

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/active-iq-unified-manager#4]
Page: [Adding clusters](https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html)

Hey doc team!  Referring to BURT 1342014. 

This line:
This account must have the admin role with Application access set to ontapi, ssh, and http.

With the fix in that BURT starting in ONTAP 9.8 it seems like we should be able to remove SSH from that list for clusters on that version.  Guess we probably need a re-confirmation from the Unified Manager engineering team.

**Comment by netapp-manini** [comment]
Hi @TimMcGue, looking into this issue. Thanks for writing in.

**Comment by netapp-manini** [comment]
Attaching the discussion here:

From: Khan, Farooq <Farooq.Khan@netapp.com> 
Sent: Tuesday, January 25, 2022 4:35 PM
To: Mandal, Manini <Manini.Mandal@netapp.com>; Hosalli, Madhava <Madhava.Hosalli@netapp.com>; Bhargava, Rakesh <Rakesh.Bhargava@netapp.com>
Cc: R, Pavan <Pavan.Kumar@netapp.com>; P, Shailaja <Shailaja.P@netapp.com>; Godavarthi, Kiran <Kiran.Godavarthi@netapp.com>; SHAIKH, ABDUN NABI <ABDUNNABI.SHAIKH@netapp.com>
Subject: Re: Doc comment on BURT 1342014

Logged burt: https://burtweb-prd.eng.netapp.com/burt/burt-bin/start?burt-id=1452466

Thanks
Farooq

From: Mandal, Manini <Manini.Mandal@netapp.com>
Date: Tuesday, 25 January 2022 at 11:36 AM
To: Khan, Farooq <Farooq.Khan@netapp.com>, Hosalli, Madhava <Madhava.Hosalli@netapp.com>, Bhargava, Rakesh <Rakesh.Bhargava@netapp.com>
Cc: R, Pavan <Pavan.Kumar@netapp.com>, P, Shailaja <Shailaja.P@netapp.com>
Subject: RE: Doc comment on BURT 1342014
Thank you, Farooq. I will add this comment to the doc issue raised. Meanwhile, when you create the BURT for engineering, please make the doc impact as Y for me to track it and attach it to the request. 
 
-Manini
 
From: Khan, Farooq <Farooq.Khan@netapp.com> 
Sent: Monday, January 24, 2022 6:23 PM
To: Hosalli, Madhava <Madhava.Hosalli@netapp.com>; Mandal, Manini <Manini.Mandal@netapp.com>; Bhargava, Rakesh <Rakesh.Bhargava@netapp.com>
Cc: R, Pavan <Pavan.Kumar@netapp.com>; P, Shailaja <Shailaja.P@netapp.com>
Subject: Re: Doc comment on BURT 1342014
 
Hi Everyone,
 
Sorry this took so long, this is very messy, this question came up in July 2020 and I had to dig up all those emails, and try and remember everything we had researched at that time.
 
Yes AIQUM needed “ssh” due the the ndmp feature and so it was in the docs. Now that the Ontap burt: 1342014 has been fixed we need to first test this, we need to confirm that just using the “ontapi” priviledge level is sufficient for us, and once this is proven we can then update AIQUM docs and remove the requirement of “ssh” priviledge level.
 
See the email discussions and testing we had done in 2020. The burt that you are referring was filed as result of this my discussion with “Srinath Vijay” in 2020. 
 
I will file a new burt in AIQUM with all this information someone in QA with expertise in this area must test this and confirm it works and then the docs can be updated.
 
Thanks
Farooq
 
From: Hosalli, Madhava <Madhava.Hosalli@netapp.com>
Date: Friday, 21 January 2022 at 1:51 PM
To: Mandal, Manini <Manini.Mandal@netapp.com>, Khan, Farooq <Farooq.Khan@netapp.com>, Bhargava, Rakesh <Rakesh.Bhargava@netapp.com>
Cc: R, Pavan <Pavan.Kumar@netapp.com>, P, Shailaja <Shailaja.P@netapp.com>
Subject: Re: Doc comment on BURT 1342014
+ Rakesh
 
 
Regards,
Madhav
________________________________________
From: Mandal, Manini <Manini.Mandal@netapp.com>
Sent: Friday, January 21, 2022 12:17 PM
To: Hosalli, Madhava <Madhava.Hosalli@netapp.com>; Khan, Farooq <Farooq.Khan@netapp.com>
Cc: R, Pavan <Pavan.Kumar@netapp.com>; P, Shailaja <Shailaja.P@netapp.com>
Subject: Doc comment on BURT 1342014 
 
Hi Farooq, Madhava,
 
We have received a doc comment WRT BURT 1342014 from a user on this UM storage management guide topic: https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html. The user is asking whether SSH should continue to be there along with ontapi and http.
 
 
On analysis, I found that the BURT states the following:
 
“This requirment in UM is because UM uses the ndmp feature, about 10 UM customers use it for sure, (based on burts filed by customers in recent years) there could be more customers using it.”
And also:
-- Author: madhavah  Date: Wed Sep 16 03:21:51 PDT 2020--------------
Do refer burt 1303314 for IE documentation, hence marking it to NO for doc_impact
 
It has been indicated in the BURT that it should be there in UM and I checked that BURT 13303314 is relevant for only ONTAP documents. Therefore, please let me know whether UM docs will continue to have SSH mentioned. 
 
Thank you,
Manini

**Comment by netapp-manini** [comment]
Hi @TimMcGue,

It has been fixed at https://docs.netapp.com/us-en/active-iq-unified-manager/storage-mgmt/task_add_clusters.html
